name = "Danny's Awesome Modpack"
author = "Danny"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "968f4f19bf512b72b614d973d78f16a808cd1304659ced663f6418b847206c3f"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
