name = "Danny's Awesome Modpack"
author = "Danny"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5018489353d576d194ad2d98680417f64bc9f17438b4944eefa84cd67299ce9"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
