name = "Danny's Awesome Modpack"
author = "Danny"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c988da47e0272f5403e22cd0f534fb6b20f7f277ec30d86bd26ffc5c9e331e42"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
