name = "Danny's Awesome Modpack"
author = "Danny"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6d82eef8675e57831715514af8d98f6674eab26e17ba989f90dc601a1afc619"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
