name = "Danny's Awesome Modpack"
author = "Danny"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9aeb00bab41a7fddc4930cf498e5632e11295ee0ba99e93ade647d54d7c11893"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
