name = "Danny's Awesome Modpack"
author = "Danny"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80016b5376d3298c9fb23b77713349730e2a274660e61bdeb3778b93396e4e7c"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
